# test-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
# nginx-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: test
  annotations:
    # Use the Traefik ingress class
    kubernetes.io/ingress.class: "traefik"

    # External DNS annotation for DNS management
    external-dns.alpha.kubernetes.io/target: 3.252.232.202  # Replace with your desired DNS name
spec:
  rules:
  - host: nginx.kubecounty.com  # Replace with your desired DNS name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
