---
- name: Create and save a self-signed SSL certificate
  hosts: all
  become: true
  tasks:
    - name: Create a private key
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/kubecert.key
        size: 2048
        state: present

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: /etc/ssl/private/kubecert.key
        common_name: kubecounty.com
        organization_name: "KubeCounty"
        country_name: "NG"
      register: csr

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/kubecert.pem
        csr_content: "{{ csr.csr }}"
        privatekey_path: /etc/ssl/private/kubecert.key
        provider: selfsigned
