---
- name: Install Cilium as the CNI on the cluster
  hosts: masters
  become: yes
  tasks:
    # Install Cilium CLI
    - name: Download and install Cilium CLI
      shell: |
        curl -L --remote-name https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
        tar xzvf cilium-linux-amd64.tar.gz
        sudo mv cilium /usr/local/bin/
      tags: cilium

    - name: Create Standard KubeConfig Dir
      file:
        path: ~/.kube
        state: directory
        mode: "0700"
      tags: cilium

    - name: Copy Kube Config to Standard KubeConfig file
      shell: |
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
      tags: cilium

    - name: Get k8sServiceHost
      shell: "kubectl get endpoints kubernetes -o jsonpath='{.subsets[0].addresses[0].ip}'"
      register: k8s_service_host
      changed_when: false

    - name: Get k8sServicePort
      shell: "kubectl get endpoints kubernetes -o jsonpath='{.subsets[0].ports[0].port}'"
      register: k8s_service_port
      changed_when: false

    # Install Cilium as the CNI
    - name: Install Cilium CNI
      shell: |
        cilium install --wait --namespace kube-system --set ipam.mode=cluster-pool  --set ipam.operator.clusterPoolIPv4PodCIDRList="10.45.0.0/16"  --set k8sServiceHost={{ k8s_service_host.stdout }}  --set k8sServicePort={{ k8s_service_port.stdout }} --set kubeProxyReplacement=true
      tags: cilium

    # Verify Cilium installation
    - name: Verify Cilium installation
      shell: |
        cilium status
      register: cilium_status
      tags: cilium

    # Output the result of Cilium status
    - name: Output Cilium installation status
      debug:
        msg: "{{ cilium_status.stdout }}"
      tags: cilium
