---
- name: Configure FRR on bastion
  hosts: localhost
  become: yes
  vars:
    frr_bgp_asn: 64513
    k3s_bgp_asn: 64512
    k3s_subnet: "10.0.2.0/24" 

  tasks:
    - name: Install FRR
      apt:
        name: 
          - frr
          - frr-pythontools
        state: present
        update_cache: yes

    - name: Enable BGP daemon
      lineinfile:
        path: /etc/frr/daemons
        regexp: '^bgpd='
        line: 'bgpd=yes'
      notify: restart frr

    - name: Configure FRR
      template:
        src: frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: ubuntu
        group: ubuntu
        mode: '0640'
      notify: restart frr

  handlers:
    - name: restart frr
      service:
        name: frr
        state: restarted