---
- name: Install K3s master and worker nodes
  hosts: all
  become: true
  tasks:
    # Task for master node
    - name: Install K3s master
      when: "'masters' in group_names"
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-backend=none --disable traefik --disable servicelb --cluster-init --disable-network-policy --disable-kube-proxy --tls-san k8s.kubecounty.com" sh -
      tags: masters

    # Task to fetch the K3s token from the master node
    - name: Fetch K3s token from master
      when: "'masters' in group_names"
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      tags: masters

    # Task to get the K3s server IP address

- name: Install K3s on workers and join them to the master
  hosts: workers
  become: yes
  tasks:
    # Install K3s on worker nodes
    - name: Install K3s worker
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://10.0.2.124:6443 \
        K3S_TOKEN={{ hostvars['master1'].k3s_token.stdout }} sh -
      tags: workers

# Setup Kubectl
- name: Configure Kubeconfig
  hosts: localhost
  become: true
  tasks:
    # Ensure the kubeconfig directory exists
    - name: Ensure Kubeconfig directory exists
      file:
        path: ~/.kube
        state: directory
        mode: "0700"
      tags: kubectl

    # Fetch the Kubeconfig file from the K3s master node
    - name: Fetch Kubeconfig from the master node
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: true
      delegate_to: master1
      tags: kubectl

    - name: Replace API server address in Kubeconfig if needed
      replace:
        path: "/home/ubuntu/.kube/config"
        regexp: '127\.0\.0\.1'
        replace: "{{ hostvars['master1'].ansible_host }}"
      when: "'127.0.0.1' in lookup('file', '~/.kube/config')"
      tags: kubectl

- name: Install Kubectl
  hosts: localhost
  become: true
  tasks:
    - name: Download kubectl
      shell: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.31.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
      register: kubectl_installed
      tags: kubectl

    # Check if kubectl is installed
    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_version
      tags: kubectl
