---
- name: Install Cilium as the CNI on the cluster
  hosts: masters
  become: yes
  tasks:
    # Install Cilium CLI
    - name: Download and install Cilium CLI
      shell: |
        curl -L --remote-name https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
        tar xzvf cilium-linux-amd64.tar.gz
        sudo mv cilium /usr/local/bin/
      tags: cilium

    - name: Create Standard KubeConfig Dir
      file:
        path: ~/.kube
        state: directory
        mode: "0700"
      tags: cilium

    - name: Copy Kube Config to Standard KubeConfig file
      shell: |
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
      tags: cilium

    # Install Cilium as the CNI
    - name: Install Cilium CNI
      shell: |
        cilium install
      tags: cilium

    # Verify Cilium installation
    - name: Verify Cilium installation
      shell: |
        cilium status
      register: cilium_status
      tags: cilium

    # Output the result of Cilium status
    - name: Output Cilium installation status
      debug:
        msg: "{{ cilium_status.stdout }}"
      tags: cilium

    # Enable Hubble
    - name: Enable Hubble
      shell: |
        cilium hubble enable
      when: "'Cilium is running' in cilium_status.stdout"
      tags: cilium

    # Verify Hubble installation
    - name: Verify Hubble installation
      shell: |
        cilium hubble status
      register: hubble_status
      when: "'Cilium is running' in cilium_status.stdout"
      tags: cilium

    # Output the result of Hubble status
    - name: Output Hubble installation status
      debug:
        msg: "{{ hubble_status.stdout }}"
      when: "'Cilium is running' in cilium_status.stdout"
      tags: cilium
