---
- name: Create and save a self-signed SSL certificate
  hosts: localhost
  become: true

  tasks:
    - name: Ensure certbot is installed
      apt:
        name: certbot
        state: present

    - name: Get Let's Encrypt certificate
      shell: |
        certbot certonly --standalone \
        -d k8s.kubecounty.com \
        --non-interactive \
        --agree-tos \
        --email malchieluriasbusiness@gmail.com
      args:
        creates: /etc/letsencrypt/live/k8s.kubecounty.com

    - name: Combine certificates for HAProxy
      shell: |
        cat /etc/letsencrypt/live/k8s.kubecounty.com/fullchain.pem \
            /etc/letsencrypt/live/k8s.kubecounty.com/privkey.pem \
            > /etc/haproxy/certs/k8s.kubecounty.com.pem
      notify: restart haproxy
