---
- name: Uninstall K3s from master and worker nodes
  hosts: all
  become: true
  tasks:
    # Task to stop K3s service (master/worker)
    - name: Stop K3s service
      shell: |
        systemctl stop k3s || systemctl stop k3s-agent
      ignore_errors: yes
      tags: uninstall

    # Task to uninstall K3s (master/worker)
    - name: Uninstall K3s
      shell: |
        /usr/local/bin/k3s-uninstall.sh || /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: yes
      tags: uninstall

    # Task to clean up any residual K3s files (optional)
    - name: Remove K3s directories and data
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s
        - /var/lib/kubelet
        - /etc/systemd/system/k3s.service
        - /etc/systemd/system/k3s-agent.service
      ignore_errors: yes
      tags: uninstall
