---
- name: Uninstall HAProxy and clear configuration
  hosts: all
  become: yes
  tasks:
    # Stop HAProxy service
    - name: Stop HAProxy service
      ansible.builtin.systemd:
        name: haproxy
        state: stopped
      tags: haproxy_uninstall

    # Uninstall HAProxy
    - name: Uninstall HAProxy package
      ansible.builtin.package:
        name: haproxy
        state: absent
      tags: haproxy_uninstall

    # Remove HAProxy configuration directory
    - name: Remove HAProxy configuration directory
      ansible.builtin.file:
        path: /etc/haproxy
        state: absent
      tags: haproxy_uninstall

    # Remove HAProxy log files
    - name: Remove HAProxy log files
      ansible.builtin.file:
        path: /var/log/haproxy.log
        state: absent
      tags: haproxy_uninstall

    # Remove HAProxy PID files
    - name: Remove HAProxy PID files
      ansible.builtin.file:
        path: /run/haproxy.pid
        state: absent
      tags: haproxy_uninstall

    # Clean up other potential residual files (optional)
    - name: Remove other HAProxy-related files
      ansible.builtin.find:
        paths:
          - /var/lib/haproxy
          - /var/run/haproxy
        recurse: yes
      register: haproxy_residual_files
      tags: haproxy_uninstall

    - name: Remove residual HAProxy files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ haproxy_residual_files.files }}"
      when: haproxy_residual_files.matched > 0
      tags: haproxy_uninstall
